apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: streamlit-container
          image: 201983195686.dkr.ecr.ap-south-1.amazonaws.com/streamlit-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: llmops-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501